kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}"
  namespace: ma-task
spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP